AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda local demo


Resources:
  LambdaDemoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda/getSchedule/tias-app # format is projectPath/
      Handler: Handler # format is filename.functionName
      Runtime: java11