INSERT INTO person (google_token_sub, email, first_name, last_name, profile_photo_url, peer_teacher, teaching_assistant, administrator, professor)
VALUES
('', '', 'Geralt', 'of Rivia', '', 'true', 'false', 'false', 'false'),
('', '', 'Gary', 'Chess', '', 'true', 'false', 'false', 'false'),
('', '', 'Sandy', 'Banks', '', 'true', 'false', 'false', 'false'),
('', '', 'King', 'Gerold III', '', 'true', 'false', 'false', 'false'),
('', '', 'Sharpness', 'IV', '', 'true', 'false', 'false', 'false'),
('', '', 'Zelda', 'DeLegendof', '', 'true', 'false', 'false', 'false'),
('', '', 'Star', 'Fox', '', 'true', 'false', 'false', 'false'),
('', '', 'Luigi', 'Smansion', '', 'true', 'false', 'false', 'false'),
('', '', 'John', 'Doom', '', 'true', 'false', 'false', 'false'),
('', '', 'Spongebob', 'Squarepants', '', 'true', 'false', 'false', 'false'),
('', '', 'Crash', 'Bandishoot', '', 'true', 'false', 'false', 'false'),
('', '', 'Suzzie', 'Sunshine', '', 'true', 'false', 'false', 'false'),
('', '', 'Mr.', 'Generic', '', 'true', 'false', 'false', 'false'),
('', '', 'Honda', 'Accord', '', 'true', 'false', 'false', 'false'),
('', '', 'K.K.', 'Slider', '', 'true', 'false', 'false', 'false'),
('', '', 'Gee', 'Wilikers', '', 'true', 'false', 'false', 'false'),
('', '', 'Mario', 'Galaxy', '', 'true', 'false', 'false', 'false'),
('', '', 'Ms.', 'Generic', '', 'true', 'false', 'false', 'false'),
('', '', 'Bubble', 'Bass', '', 'true', 'false', 'false', 'false'),
('', '', 'Sandy', 'Cheeks', '', 'true', 'false', 'false', 'false'),
('', '', 'Patrick', '', '', 'true', 'false', 'false', 'false'),
('', '', 'Samus', 'Errands', '', 'true', 'false', 'false', 'false'),
('', '', 'Timmy', 'Twix', '', 'true', 'false', 'false', 'false'),
('', '', 'Marvin', 'M&M', '', 'true', 'false', 'false', 'false'),
('', '', 'Bikeal', 'Roads', '', 'true', 'false', 'false', 'false'),
('', '', 'Spicy', 'Peppers', '', 'true', 'false', 'false', 'false'),
('', '', 'Quintin', 'QWERTY', '', 'true', 'false', 'false', 'false'),
('', '', 'Asmorald', 'ASDF', '', 'true', 'false', 'false', 'false'),
('', '', 'Timmothy', 'Tingle', '', 'true', 'false', 'false', 'false'),
('', '', 'Kimmothy', 'Kartz', '', 'true', 'false', 'false', 'false'),
('', '', 'Zimmothy', 'Zions', '', 'true', 'false', 'false', 'false'),
('', '', 'Phoenix', 'Wright', '', 'true', 'false', 'false', 'false'),
('', '', 'Mia', 'Fey', '', 'true', 'false', 'false', 'false'),
('', '', 'Miles', 'Edgeworth', '', 'true', 'false', 'false', 'false'),
('', '', 'Maya', 'Fey', '', 'true', 'false', 'false', 'false'),
('', '', 'Pearl', 'Fey', '', 'true', 'false', 'false', 'false'),
('', '', 'Dick', 'Gumshoe', '', 'true', 'false', 'false', 'false'),
('', '', 'Franziska', 'von Karma', '', 'true', 'false', 'false', 'false'),
('', '', 'Ema', 'Skye', '', 'true', 'false', 'false', 'false'),
('', '', 'The', 'Judge', '', 'true', 'false', 'false', 'false'),
('', '', 'Apollo', 'Justice', '', 'true', 'false', 'false', 'false'),
('', '', 'Trucy', 'Wright', '', 'true', 'false', 'false', 'false'),
('', '', 'Athena', 'Cykes', '', 'true', 'false', 'false', 'false'),
('', '', 'Ryunosuke', 'Naruhodo', '', 'true', 'false', 'false', 'false'),
('', '', 'Susato', 'Mikotoba', '', 'true', 'false', 'false', 'false'),
('', '', 'Herlock', 'Sholmes', '', 'true', 'false', 'false', 'false'),
('', '', 'Iris', 'Wilson', '', 'true', 'false', 'false', 'false'),
('', '', 'Barok', 'van Zieks', '', 'true', 'false', 'false', 'false'),
('', '', 'Tetsutetsu', 'Tetsutetsu', '', 'true', 'false', 'false', 'false'),
('', '', 'Bobaboba', 'Bobaboba', '', 'true', 'false', 'false', 'false'),
('', '', 'Spike', 'the Cowboy', '', 'true', 'false', 'false', 'false'),
('', '', 'Guard', 'the Reserve', '', 'true', 'false', 'false', 'false'),
('', '', 'Hero', 'Sandwich', '', 'true', 'false', 'false', 'false');